Description: Applies Linux specific updates
Author: Christian Schulte <cs@schulte.it>
Last-Update: 2026-10-07

--- abagnale-0.9803.orig/Makefile
+++ abagnale-0.9803/Makefile
@@ -52,7 +52,7 @@ CONFIG=
 #CONFIG+=-DDEFAULT_ABAG_DATABASE_TARGET=\"ABAGNALE\"
 #CONFIG+=-DDEFAULT_ABAG_DATABASE_USER=\"abagnale\"
 #CONFIG+=-DDEFAULT_ABAG_HTTP_TIMEOUT_MILLIS=60000L
-#CONFIG+=-DDEFAULT_ABAG_THREAD_TIMEOUT_MILLIS=120500
+CONFIG+=-DDEFAULT_ABAG_THREAD_TIMEOUT_MILLIS=100
 #CONFIG+=-DDEFAULT_CDP_REST_URI=\"https://api.coinbase.com\"
 #CONFIG+=-DDEFAULT_CDP_WS_URI=\"wss://advanced-trade-ws.coinbase.com\"
 #CONFIG+=-DDEFAULT_CDP_ACCOUNT_PATH=\"/api/v3/brokerage/accounts/\"
